### ISSUE TITLE
Enhance file fetching with `ResourceInfo` and optional `ACL`

### ISSUE THREAD

**Issue by NSeydoux** [inrupt/lit-pod#165]
**Search terms you've used**

File, ACL, ResourceInfo

**Is your feature request related to a problem? Please describe.**

When fetching a `LitDataset`, the information associated to the Resource is returned by the fetcher, while this information must be read manually in the `Response` returned by `fetchFile`. There is also an alternative `fetchLitDatasetWithAcl` function that do net exist for files. 

**Describe the solution you'd like**

1. Make it so that `fetchFile` returns the information attached to the fetched file
2. Add a function to fetch both a file and its `ACL`

**Describe alternatives you've considered**

Do all the operations manually by parsing the headers and sending additional requests.

**Comment by Vinnl** [comment]
I guess this is a duplicate of #152 (or vice versa)? :)

**Comment by NSeydoux** [comment]
Woops, 11 issues and already duplicates ^^. When completing `Search terms you've used`, I should really use the terms to search :stuck_out_tongue:

**Comment by Vinnl** [comment]
Haha, I must admit that I'm not doing that yet either, given that they're so few :P But at least it'll make these issues easier to find later, when we'll surely have millions of issues because it's such a popular project.
