### ISSUE TITLE
Match the `homepage` field in `package.json` with the actual homepage

### ISSUE THREAD

**Issue by NSeydoux** [inrupt/lit-pod#171]
**Search terms you've used**

Website, Homepage (for real this time)

**What problem are you trying to solve? Please describe.**

Once the place for the new documentation settles, it should be referenced in the `package.json`.

**What existing documentation is relevant to your problem, and why is it insufficient?**

The homepage currently advertized in the `package.json` is the GH repository, instead of the generated documentation. 

**Additional context**

N/A

**Comment by Vinnl** [comment]
Are you sure that it's not pointing to the homepage, given the `.io` domain? Or do you mean if we move it in the future?

**Comment by NSeydoux** [comment]
Oh my bad, the homepage specified in the `package.json` and https://www.npmjs.com/package/@solid/lit-pod are out of sync, and seeing the latter I didn't check the former. I guess that when we cut a point release the NPMJS info will update appropriately then.

**Comment by Vinnl** [comment]
Yeah I think so too. Another reason to cut a v0.1 soon :)
